### ISSUE TITLE
Create a home page for showcase platform information before users get logged in.

### ISSUE THREAD

**Issue by Dheerajjha451** [Dheerajjha451/CancerDetection#4]

**Comment by hbcscaj** [comment]
I CAN BUILD BASIC DESIGNS OF HOMEPAGE WITH LOGIN AND SIGNUP BUTTONS  WITH HELP OF TAILWIND CSS

**Comment by Dheerajjha451** [comment]
It is the page to show before login: create a home page that describes the platform, like different cancer predictions we are doing, providing remote consultancy, 24/7 chatbot support, news, and articles. Something similar to this: https://billy.designtocode.me/ these are two different platforms; this is only for reference. Use React make changes in the app/page.tsx attach the screenshot of design.

**Comment by hbcscaj** [comment]
Once the design is ready, I’ll update the app/page.tsx file and share the screenshot with you.

**Comment by hbcscaj** [comment]
Thanks 👍

**Comment by Dheerajjha451** [comment]
@hbcscaj are you working on this?

**Comment by Dheerajjha451** [comment]
@hbcscaj I'm removing you from the issue.
